### ISSUE TITLE
bug: Moodle fail to install editor plugins

### ISSUE THREAD

**Issue by jimsihk** [krestomatio/container_builder#113]
**Describe the bug**
With the Moodle container, when using [install-plugin-list](https://github.com/krestomatio/container_builder/blob/master/moodle/moodle40/conf/usr/libexec/moodle/install-plugin-list) to install plugin for editors (e.g. atto, tinymce), it is not installed as expected as installed to a wrong location.

**To Reproduce**
1. Run `/usr/libexec/moodle/install-plugin-list -f -p atto_multilang2`
2. Login Moodle
3. Navigate to Plugin Overview
4. The atto_multilang2 plugin is not installed

**Expected behavior**
The atto_multilang2 folder should be installed to _moodleroot_/lib/editor/atto/plugins.

**Screenshots**
```
bash-5.1$ /usr/libexec/moodle/install-plugin-list -f -p atto_multilang2
Installing plugin: atto_multilang2...
PHP Warning:  Undefined array key "atto" in Standard input code on line 60
Downloading plugin zip: atto_multilang2
Source: https://moodle.org/plugins/download.php/24580/atto_multilang2_moodle40_2021063000.zip
Destination: /tmp/moodle-plugins/e256dfc34ee5f4c53dc8538a26eb8742/atto_multilang2.zip
Destination directory already exists: /var/www/html//multilang2
Moving it to: /tmp/moodle-plugins/e256dfc34ee5f4c53dc8538a26eb8742/backup
Uncompressing to: /tmp/moodle-plugins/e256dfc34ee5f4c53dc8538a26eb8742/multilang2
Installing to: /var/www/html//multilang2
bash-5.1$
```

**Please tell us about your environment:**

* Operating System: Alpine Linux
* Where is this running (Local, Cloud Provider): Oracle Kubernetes Engine
* Storage being used (NFS, Hostpath, Gluster, etc): emptyDir in memory (moodlecode), NFS (moodledata)
* Container Image Tag: Moodle 0.4.0 (copied the script to run on Alpine 3.16.2)
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: 1.24.1

**Additional context**
We may consider adding a logic to check if the plugin name is starting with "atto_" or "tinymce_", then replace the installation folder path `$moodle_plugin_info_install_path` to _moodleroot_/lib/editor/atto/plugins or _moodleroot_/lib/editor/tinymce/plugins instead at [L135](https://github.com/krestomatio/container_builder/blob/master/moodle/moodle40/conf/usr/libexec/moodle/install-plugin-list#L135).

**Comment by jobcespedes** [comment]
Thanks for the detail and suggestion. Soon there will be a fix.
