### ISSUE TITLE
bug: Unable to install tinymce editor plugins

### ISSUE THREAD

**Issue by jimsihk** [krestomatio/container_builder#144]
**Describe the bug**
Since Moodle 4.1, the TinyMCE plugin name and path changed from `/tinymce/` to `/tiny/`. Thus the `install-plugin-list` will report error as the pattern is not recognized.

There is a need to update the script e.g. adding `'tiny' => array('dir' => 'lib/editor/tiny/plugins'),` to `install_path_directory_from_type` array in `install_path($plugin_type, $plugin_name)` while keeping the capability with Moodle 4.0 or below.

**To Reproduce**
1. Run `/usr/libexec/moodle/install-plugin-list -f -p tiny_multilang2`
2. Check the log

**Expected behavior**
The plugin should be installed without error.

**Screenshots**
```
ERROR: tiny is not a valid type!
```

**Please tell us about your environment:**

* Operating System: Ubuntu
* Where is this running ( Local, Cloud Provider): GitHub Action
* Storage being used (NFS, Hostpath, Gluster, etc): N/A
* Container Image Tag: v0.5.11
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: 22.04.4 LTS

**Additional context**
https://docs.moodle.org/dev/Creating_a_Moodle_specific_TinyMCE_plugin
https://moodledev.io/docs/4.4/apis/plugintypes/tiny

**Comment by jobcespedes** [comment]
Hi @jimsihk,

Thank you for opening this issue and submitting a PR to address it!
